[package]
name = "json-parser"
version = "0.1.0"
authors = ["himself65 <himself65@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.6.2"
